name: wseg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-version=12.4=hbda6634_3
  - cudnn=8.9.7.29=h092f7fd_3
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=12.4.5.8=h99ab3db_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=1.41.5=h5eee18b_0
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - accelerate==0.27.2
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audioread==3.0.1
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.41.1
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - ctranslate2==4.0.0
      - cycler==0.12.1
      - datasets==2.14.3
      - debugpy==1.8.2
      - decorator==4.4.2
      - defusedxml==0.7.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - evaluate==0.4.2
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - flask==3.0.3
      - flask-cors==4.0.1
      - fonttools==4.53.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gputil==1.4.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - idna==3.7
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - ipykernel==6.29.5
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiwer==3.0.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.15
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.8.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.9.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - plotly==5.22.0
      - pooch==1.8.2
      - proglog==0.1.10
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==5.27.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.1.0
      - pycparser==2.22
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - rapidfuzz==3.9.4
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.11.0
      - send2trash==1.8.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.7.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.3.7
      - stack-data==0.6.3
      - streamlit==1.36.0
      - streamlit-autorefresh==1.0.1
      - streamlit-elements==0.1.0
      - sympy==1.12.1
      - tenacity==8.4.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==2.3.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.38.2
      - triton==2.3.1
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.2
      - wandb==0.17.4
      - watchdog==4.0.1
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - xxhash==3.4.1
      - yarl==1.9.4
